name: Rocketeer
version: '1.0'
author: DerJannik
api-version: '1.21'
description: Spawns a Rocketeer
main: org.derjannik.rocketeer.Rocketeer
commands:
    rocketeer:
        description: Spawns a Rocketeer
        usage: /rocketeer [x] [y] [z] or /rocketeer egg